BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "files" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Filename"	TEXT NOT NULL,
	"Version number"	INTEGER,
	"Filepath"	TEXT NOT NULL,
	"Creator"	TEXT,
	"Status"	TEXT,
	"Duration"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO "files" VALUES (1,'video.mp3',NULL,'C:/...','Mats',NULL,NULL);
COMMIT;
